### PR TITLE
Geometry fire positionchange when altitude update

### LINKED ISSUE #2354: InfoWindow does not account for enableAltitude = false on panning
InfoWindow doesn't accurately follow the markers on panning when `enableAltitude` is set to `false`. There's always parallax effect even when all markers are drawn with a zero z-coordinate so InfoWindow looks completely detached from the markers. 

There are no workarounds for that except changing marker z-coordinate to zero and back and it basicaly would need reloading the entire map. I need dynamic `enableAltitude` to work.

### PR DESCRIPTION
**Pull request by deyihu**
fix #2354

### CODE REVIEW

**Comment by joric** [comment]
I built this branch, it doesn't fix the problem. I use dynamic enableAltitude on viewchange, like this:
```js
  map.on('viewchange', e=> {
      vectorLayer.setOptions({enableAltitude: map.getPitch()!=0});
  });
```
So markers lose parallax effect when pitch is set to 0 but InfoWindow does not. It doesn't seem like your code does anything to make InfoWindow to stay attached to the marker if enableAltitude is set to false, does it?

**Review by joric — APPROVED** [review]
I've checked it, it works.
**Upd.** not quite, there's an issue when info window opens on the initial click and the click area, see #2354.

**Review by joric — APPROVED** [review]

**Review by joric — COMMENTED** [review]
It's not quite there yet, there's an issue with the initial position.

**Comment by joric** [comment]
Tested 31977c1, it fixed the popup position/anchor but the click area for the marker is still off, sometimes it just doesn't open. I guess the whole enableAltitude option was broken since it was introduced, it doesn't not matter if it's dynamic, it happens when enableAltitude is false but markers have a non-zero z.

**Comment by deyihu** [comment]
@joric

**Comment by joric** [comment]
@deyihu tested 196cca6 looks like it fixed all the issues.

**Comment by deyihu** [comment]
@joric  thanks

**Pull request merged**
