### PR TITLE
 update baseLayer of map's constructor

### PR DESCRIPTION
**Pull request by guzhongren**
use baselayer's shorthand;upgrade jsdoc and docs

### CODE REVIEW

**Comment by fuzhenn** [comment]
docs/下的内容不要提交上来，发版本时才会自动生成

**Comment by guzhongren** [comment]
ok

**Comment by guzhongren** [comment]
已删除docs下的内容

**Comment by guzhongren** [comment]
已删除docs下的内容

**Comment by fuzhenn** [comment]
@guzhongren Thanks for your PR, the idea to enable setBaseLayer support string type is inspiring.
However, I won't merge this in, because:
* Hard coded urlTemplate in the source seems to be a bad idea, as it may change in the future.
* It saves codes to initialize baseLayer which is not a pain to users.

Thanks again!

**Pull request closed without merging**
